name: high_level_application
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  fluttertoast: ^8.2.8
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  image_gallery_saver: ^2.0.3
  path_provider: ^2.1.5
  audioplayers: ^6.1.0
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_quill: ^10.8.5
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.3.3

  # Add localization support
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl_utils: ^2.6.2

flutter:
  generate: true
  uses-material-design: true

  assets:
     - assets/audio/welcome.mp3
     - assets/images/image.jpg
     - assets/images/logo.png
     - lib/l10n/


